<#
.SYNOPSIS
    Publishes the generated winget manifests to the fork and opens a PR
    against microsoft/winget-pkgs.

.DESCRIPTION
    Requires:
      - the fork <GitHubUser>/winget-pkgs to exist;
      - manifests generated by preparer-winget.ps1;
      - an authenticated `gh` (GITHUB_TOKEN or `gh auth login`).

.EXAMPLE
    .\installer\publier-winget.ps1 -GitHubUser "hugo94z"
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$GitHubUser,
    [string]$Upstream = "microsoft/winget-pkgs",
    [string]$Publisher = "Ruche",
    [string]$PackageName = "Ruche",
    [string]$Version = "0.1.0",
    [string]$Branch = "",
    [string]$PrBodyFile = "",
    [string]$ManifestDir = ""
)

# Native commands (gh) write progress to stderr; with 'Stop' PowerShell would
# abort on harmless messages, so we manage errors explicitly.
$ErrorActionPreference = "Continue"
$root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
if (-not $Branch) { $Branch = "ruche-$Version" }
if (-not $ManifestDir) {
    $ManifestDir = Join-Path $root "winget\manifests\$($Publisher.Substring(0,1).ToLower())\$Publisher\$PackageName\$Version"
}
if (-not (Test-Path $ManifestDir)) {
    Write-Error "Manifestes introuvables : $ManifestDir`nLancez d'abord preparer-winget.ps1"
    exit 1
}

$files = @(Get-ChildItem $ManifestDir -File)
Write-Host "Manifestes a publier : $($files.Count)"
$files | ForEach-Object { Write-Host "  $($_.Name)" }

$fork = "$GitHubUser/winget-pkgs"

# 1. Verifier le fork
Write-Host "`n1) Verification du fork $fork ..."
$forkName = (& gh api "repos/$fork" --jq ".full_name") 2>$null
if ($LASTEXITCODE -ne 0 -or -not $forkName) {
    Write-Error "Le fork $fork est introuvable."
    exit 1
}
Write-Host "   OK"

# 2. Recuperer la tete de la branche par defaut du depot amont
$base = ((& gh api "repos/$Upstream" --jq ".default_branch") | Out-String).Trim()
$head = ((& gh api "repos/$fork/git/ref/heads/$base" --jq ".object.sha") | Out-String).Trim()
Write-Host "`n2) Branche amont '$base' a $head"

# 3. (Re)creer la branche de travail dans le fork
Write-Host "`n3) Branche de travail '$Branch'"
$existing = (& gh api "repos/$fork/git/ref/heads/$Branch" --jq ".ref") 2>$null
if ($LASTEXITCODE -eq 0 -and $existing) {
    & gh api -X DELETE "repos/$fork/git/refs/heads/$Branch" 2>$null | Out-Null
    Write-Host "   ancienne branche supprimee"
}
& gh api -X POST "repos/$fork/git/refs" -f "ref=refs/heads/$Branch" -f "sha=$head" 2>$null | Out-Null
if ($LASTEXITCODE -ne 0) { Write-Error "Creation de la branche impossible."; exit 1 }
Write-Host "   creee"

# 4. Envoyer les manifestes
Write-Host "`n4) Envoi des manifestes"
$prefix = "manifests/$($Publisher.Substring(0,1).ToLower())/$Publisher/$PackageName/$Version"
$failed = $false
foreach ($file in $files) {
    $content = [Convert]::ToBase64String([IO.File]::ReadAllBytes($file.FullName))
    $path = "$prefix/$($file.Name)"
    & gh api -X PUT "repos/$fork/contents/$path" `
        -f "message=Add $Publisher.$PackageName $Version - $($file.Name)" `
        -f "branch=$Branch" `
        -f "content=$content" 2>$null | Out-Null
    if ($LASTEXITCODE -ne 0) {
        Write-Host "   ! echec : $($file.Name)" -ForegroundColor Red
        $failed = $true
    } else {
        Write-Host "   + $($file.Name)"
    }
}
if ($failed) { Write-Error "Certains fichiers n'ont pas pu etre envoyes."; exit 1 }

# 5. Ouvrir la pull request
Write-Host "`n5) Pull request"
$title = "New package: $Publisher.$PackageName version $Version"
if (-not $PrBodyFile -or -not (Test-Path $PrBodyFile)) {
    $PrBodyFile = Join-Path $env:TEMP "ruche-pr-body.md"
}
if (Test-Path $PrBodyFile) {
    $pr = (& gh pr create --repo $Upstream --head "$GitHubUser`:$Branch" --base $base --title $title --body-file $PrBodyFile) 2>$null
} else {
    $pr = (& gh pr create --repo $Upstream --head "$GitHubUser`:$Branch" --base $base --title $title --body "New package $Publisher.$PackageName version $Version.") 2>$null
}
if ($LASTEXITCODE -ne 0) { Write-Error "Creation de la pull request impossible."; exit 1 }
Write-Host "`nPR : $pr" -ForegroundColor Green
